# Generated by Django 5.1.3 on 2024-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_pass', models.TextField()),
                ('user_type', models.TextField()),
            ],
        ),
    ]
